### ISSUE TITLE
Separating out auxiliary folders

### ISSUE THREAD

**Issue by ndaelman-hu** [FAIRmat-NFDI/AreaC-DOC#3]
It's kind of annoying for the navigation that we also have the folders with supporting material at the same height.
I suggest moving `docs/assests`, `docs/code/, `docs/stylesheets` to their own folder, next to `docs`.

**Comment by JosePizarro3** [comment]
I'd prefer to keep it as it is, for similarity with NOMAD. Furthermore, mkdocs automatically read stylesheets, assets, etc as documents for specific keys in the yaml.

We can also name sections folders with "01_...", "02_...", but this can be more annoying when dealing with the node graph script.

So I will keep it as it is.

**Comment by ndaelman-hu** [comment]
The problem is that it obfuscates our navigation pane in the IDE (VSCode). I first thought that we had a section called `code`.
Unless this has to be merged with the NOMAD one, I would change it tbh. Even then, I would rather change the NOMAD one...
The change is honestly trivial from the command line, but we can wait a bit to facilitate porting over our work.

**Comment by JosePizarro3** [comment]
The yaml is also reading by default the path to a folder called `docs`, hence it is easy to group things inside there. 

Don't know the details, but it might be because this is thought as being sharing a folder structure with the software itself. Thus it makes sense to keep everything under a single folder called docs, and not having 10 different subfolders for other stuff.

> The problem is that it obfuscates our navigation pane in the IDE (VSCode).

In any case, this is a minimum problem, not even sure I can call it that way.
